# Generated by Django 2.0.2 on 2018-03-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='archive',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='count',
            new_name='quantity',
        ),
    ]
