# Generated by Django 2.0.2 on 2018-03-13 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20180311_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 3, 14), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
