# Generated by Django 2.0.2 on 2018-03-14 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0003_auto_20180314_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('operation_date', models.DateField(blank=True, default=datetime.date(2018, 3, 15), verbose_name='date published')),
                ('operation', models.CharField(max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Category')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 3, 15), verbose_name='date published'),
        ),
    ]
