# Generated by Django 2.0.2 on 2018-03-15 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20180315_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='operation_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 13, 31, 718001), verbose_name='date published'),
        ),
    ]
