# Generated by Django 2.0.2 on 2018-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_log_operation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operation_date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation_time',
            field=models.TimeField(auto_now=True, verbose_name=''),
        ),
    ]
