# Generated by Django 2.0.2 on 2018-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20180326_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='unit',
            field=models.CharField(max_length=128),
        ),
    ]
