# Generated by Django 2.0.2 on 2018-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20180326_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=18),
        ),
    ]
