# Generated by Django 2.0.2 on 2018-03-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20180331_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
