# Generated by Django 2.0.2 on 2018-03-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20180331_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='document_date',
            field=models.DateField(),
        ),
    ]
