# Generated by Django 2.0.2 on 2018-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20180402_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='document_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='document_date',
            field=models.DateField(),
        ),
    ]
