# Generated by Django 2.0.2 on 2018-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20180402_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
