# Generated by Django 2.0.2 on 2018-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20180402_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
