# Generated by Django 2.0.2 on 2018-04-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_category_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['person', 'category__sequence']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
