# Generated by Django 2.0.2 on 2018-04-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20180415_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
