# Generated by Django 2.0.2 on 2018-04-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_category_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
