# Generated by Django 2.0.2 on 2018-04-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_auto_20180415_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='person',
            name='serial',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
