# Generated by Django 2.0.2 on 2018-04-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0021_auto_20180415_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('unit', models.CharField(max_length=128)),
                ('serial', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('id_number', models.CharField(blank=True, default='', max_length=18, null=True)),
                ('operation_date', models.DateField(auto_now=True, verbose_name='')),
                ('operation_time', models.TimeField(auto_now=True, verbose_name='')),
                ('operation', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'operation_date', 'operation_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['person', 'operation_date', 'operation_time']},
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
