# Generated by Django 2.0.2 on 2018-04-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20180415_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlog',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='archive.Person'),
        ),
    ]
