# Generated by Django 2.0.2 on 2018-04-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_personlog_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Person'),
        ),
    ]
