# Generated by Django 2.0.2 on 2018-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20180415_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence'], 'verbose_name': '材料名称', 'verbose_name_plural': '材料名称'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['unit', 'name'], 'verbose_name': '人员管理', 'verbose_name_plural': '人员管理'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['person', 'document_date', 'category__sequence']},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=16, verbose_name='类别号'),
        ),
        migrations.AlterField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='材料名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, verbose_name='十大类'),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=16, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='unit',
            field=models.CharField(max_length=128, verbose_name='工作单位'),
        ),
    ]
